[build]
  publish = "public"
  functions = "netlify/functions"

[[edge_functions]]
  function = "image-dimensions"
  path = "/api/image-dimensions"

[[edge_functions]]
  function = "convert-image"
  path = "/api/convert-image"

[[edge_functions]]
  function = "generate-thumbnail"
  path = "/api/generate-thumbnail"

[[edge_functions]]
  function = "analyze-image"
  path = "/api/analyze-image"

[[edge_functions]]
  function = "crop-image"
  path = "/api/crop-image"

[[edge_functions]]
  function = "resize-image"
  path = "/api/resize-image"

[[edge_functions]]
  function = "compress-image"
  path = "/api/compress-image"

[[edge_functions]]
  function = "edge-enhance"
  path = "/api/edge-enhance"